---
# tasks file for kubernetes_master

- name: Configuring Kubernetes Repository
  yum_repository:
    name: k8s
    description: Kubernetes repo
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-$basearch
    enabled: 1
    gpgcheck: 1
    gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg

- name: Basic packages required for Kubernetes:Docker,kubeadm,iproute-tc
  package:
    name:
      - docker
      - kubeadm
      - iproute-tc
    state: present

- name: starting all the services
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop: "{{ service_names }}"

- name: Docker image for kubernetes master 
  command: kubeadm config images pull

- name: configuration of docker
  copy:
    dest: /etc/docker/daemon.json
    src: daemon.json

- name: restarting docker
  service:
    name: docker
    state: restarted

- name: update kubernetes configuration file
  copy:
    dest: /etc/sysctl.d/k8s.conf
    content: |
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables = 1

- name: Restarting the services
  command: sysctl --system


- name: Create Cluster with kubeadm
  command: kubeadm init --pod-network-cidr=10.244.0.0/16 --ignore-preflight-errors=NumCPU --ignore-preflight-errors=Mem

- name: Managing Cluster as Regular User
  shell:
    cmd: |
      mkdir -p $HOME/.kube
      sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
      sudo chown $(id -u):$(id -g) $HOME/.kube/config

- name: Deploy flannel for DNS
  command: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml

- name: token for Joining the slave
  command: kubeadm token create  --print-join-command
  register: token

- name: cleaning caches
  shell: echo 3 > /proc/sys/vm/drop_caches
